name: Build

on:
  push:
    paths-ignore:
      - '.git**'
      - '*.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/dists
          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build
        run: |
          ./gradlew build
          echo "version=$(git describe --always)" >> $GITHUB_ENV

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: tomlib4j_${{ env.version }}
          path: './*/build/libs/*.jar'
